import { Student, Offering, PracticeVersion } from '../../../src/types/assessment';

export const SEED_STUDENTS: Student[] = [
  // Pekan 3 (12 Mahasiswa)
  { id: 'std-22603003', nim: '22603003', name: 'Affan Farsyah', class: '1C' },
  { id: 'std-22603004', nim: '22603004', name: 'Afiqah Azwa Safrina', class: '1C' },
  { id: 'std-22603006', nim: '22603006', name: 'Anisah Maharani', class: '1C' },
  { id: 'std-22603008', nim: '22603008', name: 'Azizul Hakim', class: '1C' },
  { id: 'std-22603010', nim: '22603010', name: 'Danendra Fairuz S.', class: '1C' },
  { id: 'std-22603012', nim: '22603012', name: 'Fadhil Bima Wijaya', class: '1C' },
  { id: 'std-22603014', nim: '22603014', name: 'I Made Radithya P.', class: '1C' },
  { id: 'std-22603017', nim: '22603017', name: 'Muhamad Azril F.', class: '1C' },
  { id: 'std-22603020', nim: '22603020', name: 'Muhammad Haidar', class: '1C' },
  { id: 'std-22603021', nim: '22603021', name: 'Muhammad Rayyan', class: '1C' },
  { id: 'std-22603025', nim: '22603025', name: 'Nareswari Putri S.', class: '1C' },
  { id: 'std-22603027', nim: '22603027', name: 'Reihan Adi Putra', class: '1C' },

  // Pekan 5 (12 Mahasiswa)
  { id: 'std-22603001', nim: '22603001', name: 'Achmad Fawzan', class: '1C' },
  { id: 'std-22603005', nim: '22603005', name: 'Andika Azis', class: '1C' },
  { id: 'std-22603007', nim: '22603007', name: 'Ayu Anugrah', class: '1C' },
  { id: 'std-22603011', nim: '22603011', name: 'Dede Irawan', class: '1C' },
  { id: 'std-22603013', nim: '22603013', name: 'Haura Hafizhah', class: '1C' },
  { id: 'std-22603016', nim: '22603016', name: 'M. Fauzan Adhitya Pratama H', class: '1C' },
  { id: 'std-22603018', nim: '22603018', name: 'Muh.Diaz Raditya B.', class: '1C' },
  { id: 'std-22603024', nim: '22603024', name: 'Nadya Zalzabila', class: '1C' },
  { id: 'std-22603028', nim: '22603028', name: 'Rudhi Adhana Zet', class: '1C' },
  { id: 'std-22603029', nim: '22603029', name: 'Salsabila Alifia', class: '1C' },
  { id: 'std-22603031', nim: '22603031', name: 'Syifa Nur Salsabila', class: '1C' },
  { id: 'std-22603035', nim: '22603035', name: 'Zahra Aulia Rahmadani', class: '1C' },

  // Pekan 7 (12 Mahasiswa)
  { id: 'std-22603002', nim: '22603002', name: 'Ade Meilan Alifia Sulaeman', class: '1C' },
  { id: 'std-22603009', nim: '22603009', name: 'Bayu Aji Saputro', class: '1C' },
  { id: 'std-22603015', nim: '22603015', name: 'Lintang Kemala Putri', class: '1C' },
  { id: 'std-22603019', nim: '22603019', name: 'Muhammad Farel Pratama', class: '1C' },
  { id: 'std-22603022', nim: '22603022', name: 'Muhammad Rofi R.', class: '1C' },
  { id: 'std-22603023', nim: '22603023', name: 'Nabila Nur Azizah', class: '1C' },
  { id: 'std-22603026', nim: '22603026', name: 'Rafi Ahmad Fauzi', class: '1C' },
  { id: 'std-22603030', nim: '22603030', name: 'Satria Bintang Ramadhan', class: '1C' },
  { id: 'std-22603032', nim: '22603032', name: 'Taufik Hidayatullah', class: '1C' },
  { id: 'std-22603033', nim: '22603033', name: 'Vina Nur Anggraeni', class: '1C' },
  { id: 'std-22603034', nim: '22603034', name: 'Wildan Maulana', class: '1C' },
  { id: 'std-22603036', nim: '22603036', name: 'Zulfa Khoirunnisa', class: '1C' },
];

export const SEED_OFFERINGS: Offering[] = [
  {
    id: 'CAD11-2026G-1C-P03',
    practiceCode: 'CAD 1.1',
    semester: 'Ganjil 2026/2027',
    class: '1C',
    semesterWeek: 3,
    calendarWeek: 34,
    dateRangeText: '17–21 Agustus 2026',
    startDate: '2026-08-17',
    endDate: '2026-08-21',
    studentIds: [
      'std-22603003', 'std-22603004', 'std-22603006', 'std-22603008',
      'std-22603010', 'std-22603012', 'std-22603014', 'std-22603017',
      'std-22603020', 'std-22603021', 'std-22603025', 'std-22603027',
    ],
    practiceVersionId: 'CAD11-R1',
    instructorName: 'Reza Febriadi Rauf, A.Md.T',
    isRosterVerified: true,
    areDatesVerified: true,
  },
  {
    id: 'CAD11-2026G-1C-P05',
    practiceCode: 'CAD 1.1',
    semester: 'Ganjil 2026/2027',
    class: '1C',
    semesterWeek: 5,
    calendarWeek: 36,
    dateRangeText: '31 Agustus–4 September 2026',
    startDate: '2026-08-31',
    endDate: '2026-09-04',
    studentIds: [
      'std-22603001', 'std-22603005', 'std-22603007', 'std-22603011',
      'std-22603013', 'std-22603016', 'std-22603018', 'std-22603024',
      'std-22603028', 'std-22603029', 'std-22603031', 'std-22603035',
    ],
    practiceVersionId: 'CAD11-R1',
    instructorName: 'Reza Febriadi Rauf, A.Md.T',
    isRosterVerified: false,
    areDatesVerified: false,
  },
  {
    id: 'CAD11-2026G-1C-P07',
    practiceCode: 'CAD 1.1',
    semester: 'Ganjil 2026/2027',
    class: '1C',
    semesterWeek: 7,
    calendarWeek: 38,
    dateRangeText: '14–18 September 2026',
    startDate: '2026-09-14',
    endDate: '2026-09-18',
    studentIds: [
      'std-22603002', 'std-22603009', 'std-22603015', 'std-22603019',
      'std-22603022', 'std-22603023', 'std-22603026', 'std-22603030',
      'std-22603032', 'std-22603033', 'std-22603034', 'std-22603036',
    ],
    practiceVersionId: 'CAD11-R1',
    instructorName: 'Reza Febriadi Rauf, A.Md.T',
    isRosterVerified: false,
    areDatesVerified: false,
  },
];

export const SEED_PRACTICE_VERSIONS: PracticeVersion[] = [
  {
    id: 'CAD11-R1',
    name: 'CAD 1.1 — Versi R1 (Standar 10 Latihan)',
    courseCode: 'CAD 1.1',
    courseName: 'Praktik CAD 1.1 — Pemodelan 2D & Dasar 3D',
    description: 'Format baku praktik CAD 1.1: 10 Latihan, 1 PDF Gabungan, 4 Aspek Soft Skill, 5 Sesi Absensi.',
    status: 'published',
    publishedAt: '2026-08-15T08:00:00Z',
    publishedBy: 'Admin Unit CAD',
    componentWeights: {
      exercises: 60,
      pdf: 15,
      softskill: 15,
      attendance: 10,
    },
    sections: [
      { id: 'exercises', buttonLabel: '10 Latihan', order: 1, weight: 60 },
      { id: 'pdf', buttonLabel: 'Output PDF', order: 2, weight: 15 },
      { id: 'softskill', buttonLabel: 'Soft Skill', order: 3, weight: 15 },
      { id: 'attendance', buttonLabel: 'Kehadiran 5 Hari', order: 4, weight: 10 },
    ],
    exercises: [
      {
        id: 'ex-l01',
        code: 'L01',
        title: 'Garis & Koordinat Relatif',
        topic: 'Dasar LINE, koordinat polar & kartesian',
        weight: 10,
        instructions: 'Buat geometri kontur dasar menggunakan koordinat absolut dan relatif sesuai dimensi.',
        isReady: true,
        criteria: [
          {
            id: 'c-l01-k1',
            code: 'K1',
            name: 'Ketepatan Ukuran & Geometri',
            weight: 30,
            descriptors: {
              4: 'Semua panjang segmen, sudut, dan hubungan geometri presisi 100%.',
              3: 'Ukuran tepat, ada 1 deviasi sudut minor < 0.5 derajat.',
              2: 'Terdapat 2-3 kesalahan dimensi atau penutupan garis tidak rapat.',
              1: 'Banyak ukuran salah dan bentuk kontur terdistorsi.',
              0: 'Tidak ada usaha pembuatan atau gambar salah total.',
            },
          },
          {
            id: 'c-l01-k2',
            code: 'K2',
            name: 'Kerapian & Ketebalan Garis (Layer)',
            weight: 40,
            descriptors: {
              4: 'Layer, linetype, lineweight, dan penamaan objek sempurna sesuai standar ISO.',
              3: 'Layer dan tipe garis sesuai, ada 1 kesalahan kecil pada properti warna/lineweight.',
              2: 'Beberapa objek digambar pada layer default (Layer 0) tanpa standardisasi.',
              1: 'Tidak menggunakan layer secara konsisten, tampilan garis berantakan.',
              0: 'Tidak ada pembagian layer sama sekali.',
            },
          },
          {
            id: 'c-l01-k3',
            code: 'K3',
            name: 'Pemberian Dimensi & Notasi',
            weight: 20,
            descriptors: {
              4: 'Dimensi lengkap, gaya teks standar, posisi anak panah dan jarak ekstensi rapi.',
              3: 'Dimensi lengkap, ada sedikit tumpang tindih teks dimensi minor.',
              2: 'Ada 1-2 dimensi utama terlewat, ukuran teks tidak proporsional.',
              1: 'Banyak dimensi hilang dan notasi membingungkan.',
              0: 'Tidak ada dimensi yang disertakan.',
            },
          },
          {
            id: 'c-l01-k4',
            code: 'K4',
            name: 'Efisiensi Langkah & Kecepatan',
            weight: 10,
            descriptors: {
              4: 'Selesai tepat waktu dengan alur perintah CAD yang efisien dan bersih.',
              3: 'Selesai tepat waktu dengan beberapa pengulangan perintah minor.',
              2: 'Selesai terlambat < 15 menit dari batas waktu sesi.',
              1: 'Selesai terlambat > 30 menit atau membutuhkan bantuan intensif instruktur.',
              0: 'Tidak menyelesaikan latihan dalam batas sesi.',
            },
          },
        ],
      },
      {
        id: 'ex-l02',
        code: 'L02',
        title: 'Lingkaran, Busur & Tangensial',
        topic: 'Circle, Arc, Tangent Osnap',
        weight: 10,
        instructions: 'Konstruksi hubungan tangensial halus antara busur lingkaran dan garis lurus.',
        isReady: true,
        criteria: [
          {
            id: 'c-l02-k1',
            code: 'K1',
            name: 'Ketepatan Radius & Tangensial',
            weight: 30,
            descriptors: {
              4: 'Semua titik temu busur dan garis mulus sempurna tanpa sudut patah.',
              3: 'Hubungan tangensial tepat, ada 1 titik sambung sedikit kurang presisi.',
              2: 'Radius tidak sesuai pada 1-2 segmen, transisi terlihat patah.',
              1: 'Banyak kesalahan radius dan tidak terbentuk kurva tangensial.',
              0: 'Tidak dikerjakan.',
            },
          },
          {
            id: 'c-l02-k2',
            code: 'K2',
            name: 'Kerapian Garis Sumbu & Centerline',
            weight: 40,
            descriptors: {
              4: 'Garis sumbu simetri dan tanda pusat lingkaran terpasang rapi sesuai standar.',
              3: 'Garis sumbu terpasang, panjang ekstensi sedikit tidak seragam.',
              2: 'Beberapa lingkaran tidak memiliki garis sumbu/center mark.',
              1: 'Tidak ada garis sumbu standar pada lingkaran/busur.',
              0: 'Format garis tidak teratur.',
            },
          },
          {
            id: 'c-l02-k3',
            code: 'K3',
            name: 'Pemberian Dimensi Radius & Diameter',
            weight: 20,
            descriptors: {
              4: 'Simbol R dan Ø ditempatkan sesuai kaidah gambar teknik.',
              3: 'Simbol dimensi tepat, ada 1 penempatan teks dimensi kurang ideal.',
              2: 'Tertukar penggunaan notasi R dan Ø pada fitur lingkaran.',
              1: 'Banyak dimensi radius tidak tercantum.',
              0: 'Tanpa dimensi.',
            },
          },
          {
            id: 'c-l02-k4',
            code: 'K4',
            name: 'Efisiensi Perintah CAD',
            weight: 10,
            descriptors: {
              4: 'Menggunakan object snap (tan, cen, quad) dengan sangat tangkas.',
              3: 'Penggunaan snap baik dan alur lancar.',
              2: 'Beberapa kali kesulitan menentukan titik tangen.',
              1: 'Metode pembuatan manual tanpa bantuan snap yang memadai.',
              0: 'Tidak tuntas.',
            },
          },
        ],
      },
      {
        id: 'ex-l03',
        code: 'L03',
        title: 'Modifikasi Objek & Transformasi',
        topic: 'Offset, Trim, Extend, Fillet, Chamfer',
        weight: 10,
        instructions: 'Gunakan perintah modifikasi untuk membentuk kontur profil mekanikal kompleks.',
        isReady: true,
        criteria: [
          {
            id: 'c-l03-k1',
            code: 'K1',
            name: 'Ketepatan Offset & Fillet',
            weight: 30,
            descriptors: {
              4: 'Jarak offset dan radius fillet presisi di setiap lekukan.',
              3: 'Ada 1 fillet yang memiliki radius menyimpang minor.',
              2: 'Offset tidak sejajar sempurna atau ada garis dobel.',
              1: 'Banyak geometri rusak akibat salah pemotongan (trim).',
              0: 'Tidak ada hasil modifikasi.',
            },
          },
          {
            id: 'c-l03-k2',
            code: 'K2',
            name: 'Kebersihan Garis Hasil Trim',
            weight: 40,
            descriptors: {
              4: 'Tidak ada segmen garis sisa/overlap yang tertinggal.',
              3: 'Hasil trim bersih, ada 1 titik garis overlap mikroskopis.',
              2: 'Terdapat 2-3 sisa garis potong yang tidak dibersihkan.',
              1: 'Banyak garis tumpang tindih yang merusak tampilan.',
              0: 'Kotor dan tidak dirapikan.',
            },
          },
          {
            id: 'c-l03-k3',
            code: 'K3',
            name: 'Dimensi Profil Hasil Modifikasi',
            weight: 20,
            descriptors: {
              4: 'Seluruh fillet, chamfer, dan jarak terukur rapi.',
              3: 'Ada 1 dimensi chamfer kurang jelas.',
              2: 'Dimensi tidak lengkap.',
              1: 'Banyak dimensi salah.',
              0: 'Tanpa dimensi.',
            },
          },
          {
            id: 'c-l03-k4',
            code: 'K4',
            name: 'Kemandirian Kerja',
            weight: 10,
            descriptors: {
              4: 'Mandiri dan menguasai variasi opsi perintah (Trim/Extend).',
              3: 'Mandiri dengan 1 kali konfirmasi instruktur.',
              2: 'Memerlukan bimbingan pada langkah kompleks.',
              1: 'Bergantung pada panduan teman/instruktur.',
              0: 'Tidak mampu menyelesaikan.',
            },
          },
        ],
      },
      {
        id: 'ex-l04',
        code: 'L04',
        title: 'Pola Duplikasi Array & Mirror',
        topic: 'Rectangular & Polar Array, Mirror',
        weight: 10,
        instructions: 'Buat komponen simetris dan pola lubang melingkar flange menggunakan Array dan Mirror.',
        isReady: true,
        criteria: [
          {
            id: 'c-l04-k1',
            code: 'K1',
            name: 'Pola Distribusi & Jumlah Objek',
            weight: 30,
            descriptors: {
              4: 'Jumlah item, sudut sebar 360°, dan jarak antar elemen 100% presisi.',
              3: 'Pola tepat, ada 1 sudut orientasi objek array tidak memutar.',
              2: 'Jumlah item benar tapi jarak/radius PCD meleset.',
              1: 'Pola berantakan dan tidak simetris.',
              0: 'Tidak selesai.',
            },
          },
          {
            id: 'c-l04-k2',
            code: 'K2',
            name: 'Simetri & Garis Referensi',
            weight: 40,
            descriptors: {
              4: 'Sumbu cermin tepat, garis PCD (Pitch Circle Diameter) berstandar ISO.',
              3: 'Pola simetris, tipe garis PCD sedikit kurang jelas.',
              2: 'Sumbu cermin bergeser dari titik tengah.',
              1: 'Tidak menggunakan sumbu simetri standar.',
              0: 'Salah total.',
            },
          },
          {
            id: 'c-l04-k3',
            code: 'K3',
            name: 'Dimensi Sudut & Pola',
            weight: 20,
            descriptors: {
              4: 'Notasi misal "6x Ø10 EQ SP ON Ø80 PCD" tercantum sempurna.',
              3: 'Notasi ada dengan penulisan sedikit berbeda.',
              2: 'Hanya mencantumkan ukuran 1 lubang tanpa notasi jumlah pola.',
              1: 'Dimensi tidak lengkap.',
              0: 'Tanpa dimensi.',
            },
          },
          {
            id: 'c-l04-k4',
            code: 'K4',
            name: 'Waktu Penyelesaian',
            weight: 10,
            descriptors: {
              4: 'Selesai sangat cepat memanfaatkan fitur array.',
              3: 'Selesai tepat waktu.',
              2: 'Selesai dengan keterlambatan minor.',
              1: 'Membuat satu per satu tanpa fitur array.',
              0: 'Tidak selesai.',
            },
          },
        ],
      },
      {
        id: 'ex-l05',
        code: 'L05',
        title: 'Arsir (Hatch) & Garis Potongan',
        topic: 'Hatch pattern, Section lines, Cutting Plane',
        weight: 10,
        instructions: 'Gambarkan tampak potongan parsial dan terapkan pola arsir ANSI31 dengan skala proporsional.',
        isReady: true,
        criteria: [
          {
            id: 'c-l05-k1',
            code: 'K1',
            name: 'Skala & Sudut Arsir (Hatch)',
            weight: 30,
            descriptors: {
              4: 'Pola ANSI31/ISO rapat proporsional, sudut 45°, tidak menembus batas kontur.',
              3: 'Pola arsir baik, skala sedikit terlalu rapat/renggang.',
              2: 'Arsir menimpa teks/dimensi atau skala arsir tidak proporsional.',
              1: 'Pola arsir bocor keluar bidang potong.',
              0: 'Tidak ada arsir.',
            },
          },
          {
            id: 'c-l05-k2',
            code: 'K2',
            name: 'Garis Bidang Potong & Arah Panah',
            weight: 40,
            descriptors: {
              4: 'Garis potong tebal bertitik dengan tanda panah arah pandang A-A sempurna.',
              3: 'Garis potong ada, panah arah pandang sedikit kurang proporsional.',
              2: 'Garis potong menggunakan tipe garis standar biasa.',
              1: 'Tidak ada notasi arah potong.',
              0: 'Salah konsep potongan.',
            },
          },
          {
            id: 'c-l05-k3',
            code: 'K3',
            name: 'Pemberian Label Potongan',
            weight: 20,
            descriptors: {
              4: 'Judul potongan "POTONGAN A-A" dan skala tercantum rapi.',
              3: 'Label ada, ukuran teks sedikit berbeda.',
              2: 'Label tidak lengkap.',
              1: 'Tidak diberi label penjelas.',
              0: 'Tanpa label.',
            },
          },
          {
            id: 'c-l05-k4',
            code: 'K4',
            name: 'Pengaturan Boundary Hatch',
            weight: 10,
            descriptors: {
              4: 'Boundary asosiatif dan terpisah pada setiap pulau komponen.',
              3: 'Boundary baik.',
              2: 'Beberapa area tertutup tidak terarsir.',
              1: 'Mengalami error boundary berkali-kali.',
              0: 'Gagal membuat hatch.',
            },
          },
        ],
      },
      {
        id: 'ex-l06',
        code: 'L06',
        title: 'Blok Standar & Atribut',
        topic: 'Block Creation, Attribute Definition, Library',
        weight: 10,
        instructions: 'Buat library blok baut/mur dan etiket dinamis dengan atribut teks NIM/Nama/Judul.',
        isReady: true,
        criteria: [
          {
            id: 'c-l06-k1',
            code: 'K1',
            name: 'Titik Acuan (Base Point) Blok',
            weight: 30,
            descriptors: {
              4: 'Base point berada di titik logis (tengah/sudut acuan) memudahkan insert.',
              3: 'Base point baik, sedikit bergeser dari titik tengah simetri.',
              2: 'Base point berada di koordinat (0,0) jauh dari objek.',
              1: 'Kesulitan saat memasukkan blok ke gambar utama.',
              0: 'Tidak dibuat sebagai blok.',
            },
          },
          {
            id: 'c-l06-k2',
            code: 'K2',
            name: 'Atribut Teks & Penamaan Blok',
            weight: 40,
            descriptors: {
              4: 'Atribut tag, prompt, dan default value terdefinisi rapi.',
              3: 'Atribut berfungsi, ada 1 prompt kurang deskriptif.',
              2: 'Atribut tidak menggunakan justifikasi teks yang tepat (tumpah dari kotak).',
              1: 'Teks statis, tidak memanfaatkan fitur atribut dinamis.',
              0: 'Tidak ada atribut.',
            },
          },
          {
            id: 'c-l06-k3',
            code: 'K3',
            name: 'Konsistensi Layer Blok',
            weight: 20,
            descriptors: {
              4: 'Blok dibuat pada Layer 0 sehingga mewarisi layer saat disisipkan.',
              3: 'Layer blok baik.',
              2: 'Blok terkunci pada layer tertentu.',
              1: 'Sifat layer bentrok.',
              0: 'Tidak terstruktur.',
            },
          },
          {
            id: 'c-l06-k4',
            code: 'K4',
            name: 'Kemandirian Pengujian',
            weight: 10,
            descriptors: {
              4: 'Menguji blok dengan perintah Insert dan BEdit secara mandiri.',
              3: 'Pengujian mandiri.',
              2: 'Perlu panduan instruktur saat edit blok.',
              1: 'Tidak mengerti konsep atribut.',
              0: 'Gagal.',
            },
          },
        ],
      },
      {
        id: 'ex-l07',
        code: 'L07',
        title: 'Proyeksi Orthogonal & Isometri',
        topic: 'Orthographic 3 Pandangan & Isodraft',
        weight: 10,
        instructions: 'Gambarkan 3 pandangan proyeksi Amerika/Eropa dan gambar isometrik objek mesin 3D semu.',
        isReady: true,
        criteria: [
          {
            id: 'c-l07-k1',
            code: 'K1',
            name: 'Keselarasan Proyeksi (Alignment)',
            weight: 30,
            descriptors: {
              4: 'Pandangan depan, atas, dan samping terproyeksi lurus dan sejajar sempurna.',
              3: 'Proyeksi sejajar, ada 1 garis proyeksi bantu belum dihapus.',
              2: 'Jarak antar pandangan tidak seimbang atau tidak selaras.',
              1: 'Salah meletakkan posisi pandangan (tertukar atas/samping).',
              0: 'Bukan gambar proyeksi standar.',
            },
          },
          {
            id: 'c-l07-k2',
            code: 'K2',
            name: 'Garis Tersembunyi (Hidden Lines)',
            weight: 40,
            descriptors: {
              4: 'Garis putus-putus (DASHED) fitur tak terlihat lengkap dan berskala tepat.',
              3: 'Garis tersembunyi ada, ada 1 segmen kurang proporsional.',
              2: 'Ada 1-2 fitur tersembunyi tidak digambar dengan garis putus-putus.',
              1: 'Garis tersembunyi digambar garis kontinu padat.',
              0: 'Tidak ada garis tersembunyi.',
            },
          },
          {
            id: 'c-l07-k3',
            code: 'K3',
            name: 'Gambar Isometri (Sudut 30°)',
            weight: 20,
            descriptors: {
              4: 'Isocircle pada isoplane (top, left, right) presisi sempurna.',
              3: 'Isometri rapi, ada 1 elips isocircle sedikit salah orientasi.',
              2: 'Gambar isometri tidak menggunakan sudut 30° standar.',
              1: 'Gambar isometri terdistorsi.',
              0: 'Tidak ada gambar isometri.',
            },
          },
          {
            id: 'c-l07-k4',
            code: 'K4',
            name: 'Kerapian Etiket & Layout',
            weight: 10,
            descriptors: {
              4: 'Penataan gambar di dalam kertas sangat proporsional.',
              3: 'Penataan baik.',
              2: 'Gambar terlalu padat di satu sudut kertas.',
              1: 'Gambar keluar dari garis tepi.',
              0: 'Berantakan.',
            },
          },
        ],
      },
      {
        id: 'ex-l08',
        code: 'L08',
        title: 'Toleransi Geometris & Fit',
        topic: 'GD&T, Fit Tolerances, Surface Finish',
        weight: 10,
        instructions: 'Lengkapi gambar kerja dengan simbol toleransi bentuk/posisi (GD&T) dan nilai kekasaran permukaan.',
        isReady: true,
        criteria: [
          {
            id: 'c-l08-k1',
            code: 'K1',
            name: 'Simbol GD&T & Datum Acuan',
            weight: 30,
            descriptors: {
              4: 'Kotak kontrol fitur toleransi (Feature Control Frame) dan datum A, B terpasang benar.',
              3: 'Simbol GD&T tepat, panah datum sedikit miring.',
              2: 'Simbol toleransi salah kategori (misal paralelisme pada sumbu silinder).',
              1: 'Penulisan simbol manual tanpa menggunakan perintah Tolerance CAD.',
              0: 'Tanpa GD&T.',
            },
          },
          {
            id: 'c-l08-k2',
            code: 'K2',
            name: 'Notasi Toleransi Linear (Fit H7/g6)',
            weight: 40,
            descriptors: {
              4: 'Toleransi poros dan lubang dicantumkan dengan kelas suaian standar ISO.',
              3: 'Toleransi tercantum, angka deviasi atas/bawah sesuai.',
              2: 'Format tulisan toleransi tidak sejajar dengan ukuran nominal.',
              1: 'Nilai toleransi salah atau asal-asalan.',
              0: 'Tanpa toleransi.',
            },
          },
          {
            id: 'c-l08-k3',
            code: 'K3',
            name: 'Simbol Tuntutan Permukaan (Roughness)',
            weight: 20,
            descriptors: {
              4: 'Simbol segitiga Ra ditempatkan tegak lurus pada bidang kerja.',
              3: 'Simbol permukaan ada dan terbaca jelas.',
              2: 'Penempatan simbol terbalik terhadap orientasi pembacaan gambar.',
              1: 'Simbol salah bentuk.',
              0: 'Tanpa simbol permukaan.',
            },
          },
          {
            id: 'c-l08-k4',
            code: 'K4',
            name: 'Kerapian Notasi Khusus',
            weight: 10,
            descriptors: {
              4: 'Gambar terlihat profesional memenuhi standar manufaktur industri.',
              3: 'Gambar rapi.',
              2: 'Notasi terlalu berdesakan dengan dimensi utama.',
              1: 'Gambar sulit dibaca oleh operator.',
              0: 'Gagal.',
            },
          },
        ],
      },
      {
        id: 'ex-l09',
        code: 'L09',
        title: 'Gambar Rakitan Sederhana (Assembly)',
        topic: 'Komponen Rakitan 2D & Bill of Materials (BOM)',
        weight: 10,
        instructions: 'Susun komponen pasangan (pin, bushing, link) menjadi rakitan utuh dan buat tabel daftar bagian (BOM).',
        isReady: true,
        criteria: [
          {
            id: 'c-l09-k1',
            code: 'K1',
            name: 'Kesesuaian Rakitan & Posisi Pasangan',
            weight: 30,
            descriptors: {
              4: 'Semua komponen terpasang pada sumbu kontak yang benar tanpa benturan/clash.',
              3: 'Rakitan tepat, ada sedikit pergeseran pada posisi ring pengunci.',
              2: 'Terdapat komponen yang melayang (tidak duduk pada bidang acuan).',
              1: 'Rakitan salah posisi dan tidak berfungsi.',
              0: 'Tidak ada gambar rakitan.',
            },
          },
          {
            id: 'c-l09-k2',
            code: 'K2',
            name: 'Tabel Daftar Bagian (Bill of Materials)',
            weight: 40,
            descriptors: {
              4: 'Kolom No, Nama Bagian, Jumlah, Material, dan Keterangan terisi lengkap.',
              3: 'Tabel BOM rapi, ada 1 spesifikasi material belum dicantumkan.',
              2: 'Tabel dibuat manual tanpa struktur kolom standar CAD.',
              1: 'Banyak komponen rakitan terlewat dari daftar BOM.',
              0: 'Tanpa tabel BOM.',
            },
          },
          {
            id: 'c-l09-k3',
            code: 'K3',
            name: 'Nomor Balon Penunjuk (Item Balloons)',
            weight: 20,
            descriptors: {
              4: 'Balon penunjuk bernomor terhubung dengan panah ke setiap komponen dan berurutan.',
              3: 'Balon nomor ada, garis penunjuk sedikit berpotongan.',
              2: 'Ada nomor balon yang tidak cocok dengan nomor baris tabel BOM.',
              1: 'Nomor penunjuk tidak jelas.',
              0: 'Tanpa balon penunjuk.',
            },
          },
          {
            id: 'c-l09-k4',
            code: 'K4',
            name: 'Dimensi Utama Rakitan (Overall Dimensions)',
            weight: 10,
            descriptors: {
              4: 'Hanya mencantumkan dimensi total dan jarak pusat fungsional (bukan dimensi detail).',
              3: 'Dimensi utama lengkap.',
              2: 'Masih mencantumkan terlalu banyak dimensi detail komponen.',
              1: 'Dimensi rakitan membingungkan.',
              0: 'Tanpa dimensi.',
            },
          },
        ],
      },
      {
        id: 'ex-l10',
        code: 'L10',
        title: 'Tata Letak Layout & Konfigurasi Plotting',
        topic: 'Paper Space Layout, Viewport Scaling, Page Setup',
        weight: 10,
        instructions: 'Atur gambar pada Layout kertas A4/A3, kunci skala viewport (1:1, 1:2), dan siapkan etiket resmi.',
        isReady: true,
        criteria: [
          {
            id: 'c-l10-k1',
            code: 'K1',
            name: 'Skala Viewport & Kunci Tampilan',
            weight: 30,
            descriptors: {
              4: 'Skala viewport standar tepat (misal 1:1), viewport terkunci (Display Locked: Yes).',
              3: 'Skala tepat, viewport lupa dikunci.',
              2: 'Skala viewport menggunakan angka desimal tidak standar (misal 1:1.37).',
              1: 'Gambar tidak masuk ke dalam viewport dengan benar.',
              0: 'Tidak menggunakan paper space layout.',
            },
          },
          {
            id: 'c-l10-k2',
            code: 'K2',
            name: 'Kelengkapan Etiket Gambar (Title Block)',
            weight: 40,
            descriptors: {
              4: 'Etiket resmi terisi lengkap: Nama, NIM, Kelas, Tanggal, Skala, No Lembar, TTD Instruktur.',
              3: 'Etiket terisi lengkap, ada 1 data minor belum diisi.',
              2: 'Etiket terpotong oleh batas margin cetak kertas.',
              1: 'Etiket dibuat tidak standar.',
              0: 'Tanpa etiket.',
            },
          },
          {
            id: 'c-l10-k3',
            code: 'K3',
            name: 'Pengaturan Cetak & Plot Style (CTB/Monochrome)',
            weight: 20,
            descriptors: {
              4: 'Konfigurasi pen table hitam/putih tajam dengan variasi tebal garis terdefinisi jelas.',
              3: 'Plot style baik, hasil cetak terbaca jelas.',
              2: 'Semua garis tercetak dengan satu ketebalan tipis yang sama.',
              1: 'Warna kuning/hijau tercetak terang dan tidak terbaca di kertas putih.',
              0: 'Gagal plot.',
            },
          },
          {
            id: 'c-l10-k4',
            code: 'K4',
            name: 'Kerapian Tata Letak Multi-Viewport',
            weight: 10,
            descriptors: {
              4: 'Susunan tampak depan, samping, dan detail diatur sangat harmonis dan estetik.',
              3: 'Tata letak rapi.',
              2: 'Jarak antar viewport terlalu sempit.',
              1: 'Garis border viewport ikut tercetak mengotori gambar.',
              0: 'Layout berantakan.',
            },
          },
        ],
      },
    ],
    pdfRubric: [
      {
        id: 'c-pdf-k1',
        code: 'K1',
        name: 'Kelengkapan Lembar Gambar & Etiket',
        weight: 40,
        descriptors: {
          4: 'Seluruh lembar latihan (L01–L10) terkumpul lengkap dalam 1 file PDF urut dengan etiket terisi penuh.',
          3: 'Semua lembar ada, urutan lembar ada 1 yang tertukar atau etiket ada data minor kosong.',
          2: 'Terdapat 1-2 lembar latihan tidak disertakan dalam berkas PDF gabungan.',
          1: 'Banyak lembar latihan hilang (>3 lembar) atau etiket tidak diisi.',
          0: 'Berkas rusak, kosong, atau tidak mengumpulkan berkas PDF.',
        },
      },
      {
        id: 'c-pdf-k2',
        code: 'K2',
        name: 'Kualitas Garis & Standar Proyeksi ISO',
        weight: 30,
        descriptors: {
          4: 'Resolusi vektor tajam, ketebalan garis (lineweight) kontras jelas, simbol proyeksi ISO presisi.',
          3: 'Kualitas garis tajam, ada sedikit ketidakkonsistenan tebal garis pada 1 lembar.',
          2: 'Garis tampak pudar atau semua garis tercetak dengan ketebalan sama.',
          1: 'Resolusi pecah (raster buram) dan standar gambar tidak dipatuhi.',
          0: 'Gambar tidak dapat diidentifikasi.',
        },
      },
      {
        id: 'c-pdf-k3',
        code: 'K3',
        name: 'Kesesuaian Dimensi & Keterbacaan Teks',
        weight: 20,
        descriptors: {
          4: 'Semua dimensi dan teks notasi terbaca jelas, ukuran font proporsional, tidak ada tumpang tindih.',
          3: 'Teks terbaca jelas, ada 1 dimensi sedikit terlalu dekat dengan kontur gambar.',
          2: 'Beberapa teks dimensi terlalu kecil atau terpotong margin cetak.',
          1: 'Banyak dimensi buram dan tidak terbaca.',
          0: 'Tanpa dimensi.',
        },
      },
      {
        id: 'c-pdf-k4',
        code: 'K4',
        name: 'Format & Ukuran Berkas Sesuai Ketentuan',
        weight: 10,
        descriptors: {
          4: 'Nama file sesuai format baku (NIM_Nama_CAD1.1.pdf), ukuran file optimal (< 15MB).',
          3: 'Format nama file sedikit berbeda, ukuran berkas normal.',
          2: 'Ukuran file terlalu besar (> 20MB) tanpa optimasi atau nama file tidak menyertakan NIM.',
          1: 'Format file bukan PDF (misal tangkapan layar JPG/PNG).',
          0: 'Salah format total.',
        },
      },
    ],
    softSkillRubric: [
      {
        id: 'c-soft-k1',
        code: 'K1',
        name: 'Disiplin Proses & Kebersihan Lab',
        weight: 25,
        descriptors: {
          4: 'Hadir tepat waktu, mengikuti SOP lab, mematikan workstation dan merapikan meja kerja.',
          3: 'Hadir tepat waktu, merapikan meja kerja dengan 1 kali pengingat.',
          2: 'Terlambat < 15 menit atau meninggalkan meja kerja dalam kondisi kurang rapi.',
          1: 'Terlambat berulang, makan/minum di dekat workstation CAD.',
          0: 'Melanggar aturan keselamatan kerja lab secara fatal.',
        },
      },
      {
        id: 'c-soft-k2',
        code: 'K2',
        name: 'Tanggung Jawab & Ketuntasan Tugas',
        weight: 25,
        descriptors: {
          4: 'Fokus penuh selama jam praktik, menyelesaikan target harian dengan standar mutu tinggi.',
          3: 'Menyelesaikan target harian tepat waktu.',
          2: 'Sering menunda pengerjaan sehingga membutuhkan tambahan waktu sesi.',
          1: 'Meninggalkan sesi sebelum target harian selesai tanpa izin.',
          0: 'Tidak mengerjakan tugas yang diinstruksikan.',
        },
      },
      {
        id: 'c-soft-k3',
        code: 'K3',
        name: 'Kemandirian & Pemecahan Masalah',
        weight: 25,
        descriptors: {
          4: 'Mampu menganalisis kendala geometri CAD secara mandiri sebelum bertanya ke instruktur.',
          3: 'Berusaha mandiri, bertanya pada hal-hal yang bersifat prinsip.',
          2: 'Cepat menyerah saat menghadapi pesan kesalahan CAD.',
          1: 'Pasif dan menunggu disuapi instruktur/rekan kerja.',
          0: 'Menyalin file pekerjaan mahasiswa lain secara langsung.',
        },
      },
      {
        id: 'c-soft-k4',
        code: 'K4',
        name: 'Komunikasi & Etika Kerja',
        weight: 25,
        descriptors: {
          4: 'Sopan, santun dalam berkonsultasi, membantu diskusi teknis yang membangun di ruang praktik.',
          3: 'Berkomunikasi dengan baik dan kooperatif.',
          2: 'Kurang responsif saat instruktur memberikan arahan klasikal.',
          1: 'Membuat kegaduhan yang mengganggu konsentrasi mahasiswa lain.',
          0: 'Berperilaku tidak etis atau menolak arahan instruktur.',
        },
      },
    ],
    exerciseCriteria: [
      {
        id: 'crit-ex-k1',
        code: 'K1',
        name: 'Presisi Ukuran & Ketepatan Geometri',
        weight: 30,
        descriptors: {
          4: 'Semua dimensi, sudut, dan hubungan geometri presisi 100%.',
          3: 'Dimensi tepat, ada 1 deviasi minor.',
          2: 'Terdapat 2-3 kesalahan ukuran.',
          1: 'Banyak ukuran salah.',
          0: 'Tidak ada gambar yang valid.',
        },
      },
      {
        id: 'crit-ex-k2',
        code: 'K2',
        name: 'Kerapian Garis, Layer & Standardisasi',
        weight: 40,
        descriptors: {
          4: 'Layer, linetype, lineweight terdefinisi sempurna standar ISO.',
          3: 'Layer dan tipe garis sesuai standar.',
          2: 'Beberapa objek digambar pada layer default.',
          1: 'Tidak menggunakan layer secara konsisten.',
          0: 'Tanpa pembagian layer.',
        },
      },
      {
        id: 'crit-ex-k3',
        code: 'K3',
        name: 'Pemberian Dimensi & Keterbacaan Notasi',
        weight: 20,
        descriptors: {
          4: 'Dimensi lengkap, gaya teks standar, posisi rapi.',
          3: 'Dimensi lengkap dengan sedikit tumpang tindih minor.',
          2: 'Ada dimensi utama terlewat.',
          1: 'Banyak dimensi hilang.',
          0: 'Tanpa dimensi.',
        },
      },
      {
        id: 'crit-ex-k4',
        code: 'K4',
        name: 'Efisiensi Langkah & Kecepatan Kerja',
        weight: 10,
        descriptors: {
          4: 'Selesai tepat waktu dengan alur perintah CAD efisien.',
          3: 'Selesai tepat waktu.',
          2: 'Selesai terlambat < 15 menit.',
          1: 'Selesai terlambat > 30 menit.',
          0: 'Tidak menyelesaikan latihan.',
        },
      },
    ],
    attendancePolicy: {
      sessionsCount: 5,
      scores: {
        hadir: 4,
        izin: null,
        sakit: null,
        alpa: 0,
      },
    },
    passingThreshold: 75.0,
    minimumSoftSkillObservations: 1,
    maxPdfSizeMb: 20,
  },
];
